spring.datasource.url=jdbc:postgresql://localhost:5432/es2-saude-db
spring.datasource.username=postgres
spring.datasource.password=Guibeca2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true